# Header
menu:
  主页: /
  所有文章: /archives
  #随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/chanzig"
  weibo: "http://weibo.com/338944949"
  csdn: "http://blog.csdn.net/chanzig"
  segment: "http://segmentfault.com/u/kapta"
  alipay: "javascript:void(0)"
  #rss: "http://feedburner.google.com"
  
  wechat: "javascript:void(0)"
  zhihu: "http://zhihu.com/people/kapta"
  douban: "http://www.douban.com/people/chanzig/"
  mail: "mailto:kapta.fu@outlook.com"
  facebook: "#"
  google: "https://plus.google.com/u/0/101985910547042817978/posts"
  twitter: "https://twitter.com/chanzig"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
#mathjax: true

# 是否开启动画效果
animate: true

#是否使用sweetalert
sweetalert: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /img/MyImg.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: "kapta"
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  奥巴马的博客: http://localhost:4000/
  卡卡的美丽传说: http://localhost:4000/
  本泽马的博客: http://localhost:4000/
  吉格斯的博客: http://localhost:4000/
  习大大大不同: http://localhost:4000/
  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…